version: '3'

services: 
    rasscreen_db:
        build: ./db
        tty: true
        ports: 
            - "3306:3306"
        container_name: RasScreen_db
        environment: 
            MYSQL_ROOT_PASSWORD: P@ssw0rd
            MYSQL_DATABASE: rasscreen
            MYSQL_USER: user
            MYSQL_PASSWORD: P@ssw0rd

    rasscreen_golang:
        build: ./go
        tty: true
        ports:
            - "8080:8080"
        container_name: RasScreen_golang
        links:
            - rasscreen_db
            - rasscreen_react
        volumes:
            - ./go:/go/src
        environment:
            - "GOPATH=/go/src/server"

    rasscreen_react:
        build: ./react
        tty: true
        ports: 
            - "3000:3000"
        container_name: RasScreen_react
        volumes: 
            - ./react:/usr/src